spring:
  application:
    name: hello-spring
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console
